version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /fastq_subsample/fastq_subsample.wdl
    readMePath: /fastq_subsample/README.md
    authors:
      - orcid: 0000-0002-1833-4397
    name: fastq_subsample
